# Generated by Django 5.1.6 on 2026-06-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booksen_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_rank', models.SmallIntegerField(default=0)),
                ('category_code', models.IntegerField(default=0)),
                ('category_name', models.CharField(max_length=30)),
                ('top_category_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtoileBookInven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_shopify', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'etoile_book_inven',
            },
        ),
        migrations.CreateModel(
            name='EtoileBookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=255)),
                ('desc_en', models.TextField(default='')),
                ('preview_urls', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etoile_inven', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='book.etoilebookinven')),
            ],
            options={
                'db_table': 'etoile_book_info',
            },
        ),
        migrations.CreateModel(
            name='EtoileShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('variant_id', models.CharField(default='0', max_length=20)),
                ('inventory_item_id', models.CharField(default='0', max_length=20)),
                ('shopify_price', models.FloatField(default=0.0)),
                ('is_new_arrival', models.SmallIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etoile_inven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_product', to='book.etoilebookinven')),
            ],
            options={
                'db_table': 'etoile_book_shopify_product',
            },
        ),
        migrations.CreateModel(
            name='Inven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inven_SKU', models.CharField(db_index=True, max_length=40)),
                ('vendor', models.CharField(max_length=40)),
                ('store', models.CharField(max_length=40)),
                ('is_prepared', models.SmallIntegerField(default=0)),
                ('status_of_shopify', models.SmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_use', models.SmallIntegerField(default=0)),
                ('booxen_api_status', models.SmallIntegerField(default=0)),
                ('kyobo_crawl_status', models.SmallIntegerField(default=0)),
                ('yes24_crawl_status', models.SmallIntegerField(default=0)),
                ('aladin_crawl_status', models.SmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['inven_SKU', 'status_of_shopify'], name='book_inven_inven_S_f635a0_idx')],
            },
        ),
        migrations.AddField(
            model_name='etoilebookinven',
            name='inven',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='etoile_inven', to='book.inven'),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_id', models.CharField(max_length=30)),
                ('is_use', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='book.collection')),
                ('inven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='book.inven')),
            ],
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', '도서 노트'), ('SHIPPING', '출고 노트')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='book.inven')),
            ],
            options={
                'db_table': 'book_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shopify_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('variant_id', models.CharField(default='0', max_length=20)),
                ('inventory_item_id', models.CharField(default='0', max_length=20)),
                ('shopify_price', models.FloatField(default=0.0)),
                ('is_new_arrival', models.SmallIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_product', to='book.inven')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('price_sale', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=100)),
                ('useruse1', models.CharField(max_length=30)),
                ('useruse2', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('opndate', models.CharField(default='0000-00-00', max_length=10)),
                ('outrt2', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('retyn', models.CharField(max_length=2)),
                ('booxen_cate_cd1', models.IntegerField(default=0)),
                ('booxen_cate_cd2', models.IntegerField(default=0)),
                ('booxen_cate_cd3', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('kyobo_weight', models.IntegerField(default=0)),
                ('kyobo_status', models.CharField(blank=True, default='', max_length=10)),
                ('kyobo_supply_price', models.IntegerField(default=0)),
                ('yes24_weight', models.IntegerField(default=0)),
                ('aladin_weight', models.IntegerField(default=0)),
                ('manual_weight', models.IntegerField(default=0)),
                ('dim1', models.IntegerField(default=0)),
                ('dim2', models.IntegerField(default=0)),
                ('dim3', models.IntegerField(default=0)),
                ('image_detail', models.TextField(default='')),
                ('cover_image_url', models.TextField(default='')),
                ('cover_image_url2', models.TextField(default='')),
                ('desc_table', models.TextField(default='')),
                ('desc_pub', models.TextField(default='')),
                ('desc_author', models.TextField(default='')),
                ('desc_desc', models.TextField(default='')),
                ('kyobo_category1', models.CharField(blank=True, default='', max_length=30)),
                ('kyobo_category2', models.CharField(blank=True, default='', max_length=30)),
                ('kyobo_category3', models.CharField(blank=True, default='', max_length=30)),
                ('kyobo_category4', models.CharField(blank=True, default='', max_length=30)),
                ('kyobo_category5', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inven', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='book.inven')),
            ],
            options={
                'indexes': [models.Index(fields=['price_sale'], name='book_info_price_s_4c95aa_idx'), models.Index(fields=['price', 'kyobo_supply_price'], name='book_info_price_04bb95_idx')],
            },
        ),
    ]
