# Generated by Django 5.1.6 on 2026-06-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_store_t_486ac6_idx',
            old_name='order_order_store_t_9610fa_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_financi_dc2906_idx',
            old_name='order_order_financi_7dc30c_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_fulfill_5569fe_idx',
            old_name='order_order_fulfill_3f598b_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_shopify_8b68b7_idx',
            old_name='order_order_shopify_c3e089_idx',
        ),
        migrations.AlterModelTable(
            name='billingaddress',
            table='orders_billing_address',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='orders_customer',
        ),
        migrations.AlterModelTable(
            name='lineitem',
            table='orders_line_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='orders_refund',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='orders_shipping_address',
        ),
        migrations.AlterModelTable(
            name='shippingline',
            table='orders_shipping_line',
        ),
    ]
