# Generated by Django 5.1.6 on 2026-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_tables_orders_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorVendorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=255, unique=True)),
                ('distributor', models.CharField(choices=[('choeumgoyuk', '처음교육'), ('agape', '아가페')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders_distributorvendorrule',
                'indexes': [models.Index(fields=['publisher_name'], name='orders_dist_publish_0de448_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('bookseen_available', models.BooleanField(blank=True, null=True)),
                ('bookseen_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kyobo_available', models.BooleanField(blank=True, null=True)),
                ('kyobo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selected_distributor', models.CharField(blank=True, choices=[('bookseen', '북센'), ('kyobo', '교보')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_vendorcomparison',
                'indexes': [models.Index(fields=['sku'], name='orders_vend_sku_f82fd9_idx')],
                'unique_together': {('sku',)},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('distributor', models.CharField(choices=[('bookseen', '북센'), ('kyobo', '교보'), ('choeumgoyuk', '처음교육'), ('agape', '아가페')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', '발주 대기'), ('confirmed', '발주 확정'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_items', models.ManyToManyField(blank=True, related_name='purchase_orders', to='order.lineitem')),
            ],
            options={
                'db_table': 'orders_purchaseorder',
                'indexes': [models.Index(fields=['distributor'], name='orders_purc_distrib_d364ec_idx'), models.Index(fields=['status'], name='orders_purc_status_f227fe_idx'), models.Index(fields=['created_at'], name='orders_purc_created_3fb6af_idx'), models.Index(fields=['sku'], name='orders_purc_sku_0edad4_idx')],
            },
        ),
    ]
