# Generated by Django 5.1.6 on 2026-06-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_purchase_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcomparison',
            name='bookseen_arrival',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='bookseen_returnable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='bookseen_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='bookseen_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_returnable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
