# Generated by Django 5.1.6 on 2026-06-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_vendorcomparison_add_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_ordered_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='kyobo_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
