# Generated by Django 5.1.6 on 2026-06-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_vendorcomparison_kyobo_publisher_qty_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[('korea', '한국'), ('ca', 'CA'), ('nj', 'NJ')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_warehousestock',
                'indexes': [models.Index(fields=['isbn'], name='orders_ware_isbn_e0a07d_idx')],
                'unique_together': {('isbn', 'location')},
            },
        ),
    ]
