# Generated by Django 5.1.6 on 2026-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_add_warehousestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcomparison',
            name='candidate_basis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='price_diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendorcomparison',
            name='price_diff_alert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcomparison',
            name='selected_distributor',
            field=models.CharField(blank=True, choices=[('bookseen', '북센'), ('kyobo', '교보'), ('warehouse', '재고'), ('warehouse_west', '재고-서부확인'), ('check_required', '확인필요'), ('choeumgoyuk', '처음교육'), ('agape', '아가페')], max_length=20, null=True),
        ),
    ]
