# Generated by Django 5.1.6 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_vendorcomparison_candidate_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
