# Generated by Django migration for SPEC-ORDER-006

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_add_note_resolved_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
