# Generated by Django 5.1.6 on 2026-06-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_lineitem_add_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='purchase_status',
            field=models.CharField(choices=[('unordered', '미발주'), ('on_hold', '주문보류'), ('order_cancelled', '주문취소'), ('other_publisher', '타출판사'), ('cs_required', 'CS필요'), ('in_stock', '재고')], default='unordered', max_length=20),
        ),
    ]
