# Generated by Django 5.1.6 on 2026-06-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_add_sungseoyunion_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_exchangerate',
            },
        ),
        migrations.RenameIndex(
            model_name='bookseendata',
            new_name='orders_book_sku_341531_idx',
            old_name='orders_book_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='kyobodata',
            new_name='orders_kyob_sku_727e19_idx',
            old_name='orders_kyob_sku_idx',
        ),
        migrations.AlterField(
            model_name='bookseendata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kyobodata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['effective_date'], name='orders_exch_effecti_0049e3_idx'),
        ),
    ]
