# Generated by Django 5.1.6 on 2026-06-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_create_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='source',
        ),
    ]
