# Generated by Django 5.1.6 on 2026-06-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_exchangerate_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='note',
        ),
        migrations.CreateModel(
            name='LineItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('assignee', models.CharField(blank=True, choices=[('CS', 'CS'), ('발주', '발주'), ('한국창고', '한국창고'), ('미국창고', '미국창고')], default='CS', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_item_notes', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='order.lineitem')),
            ],
            options={
                'db_table': 'orders_line_item_note',
                'ordering': ['-created_at'],
            },
        ),
    ]
