# Generated by Django 5.1.6 on 2026-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_add_line_item_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifySkuSetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_sku', models.CharField(db_index=True, max_length=200)),
                ('member_isbn', models.CharField(max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_shopify_sku_set_mapping',
                'ordering': ['bundle_sku', 'sort_order'],
                'indexes': [models.Index(fields=['bundle_sku'], name='order_shopi_bundle__11c978_idx')],
                'unique_together': {('bundle_sku', 'member_isbn')},
            },
        ),
    ]
