# Generated by Django 5.1.6 on 2026-07-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_rename_bookseen_to_booxen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yes24Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_yes24data',
                'indexes': [models.Index(fields=['sku'], name='orders_yes2_sku_a10907_idx')],
            },
        ),
    ]
