# Generated by Django 5.1.6 on 2026-07-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_yes24data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together={('order', 'shopify_line_item_id', 'sku')},
        ),
    ]
