# Generated by Django 5.1.6 on 2026-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_backfill_bundle_title_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyobodata',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
