# Generated by Django 5.1.6 on 2026-08-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_lineitem_add_shipped_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['name'], name='orders_orde_name_f179b7_idx'),
        ),
    ]
