# Generated by Django 5.1.6 on 2026-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_lineitem_add_received_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refund',
            unique_together={('order', 'shopify_refund_id', 'line_item_id')},
        ),
    ]
