# Generated by Django 5.1.6 on 2026-08-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_backfill_ready_to_ship_damaged_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSyncWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(choices=[('gimssine', 'Gimssine'), ('etoile', 'Etoile')], max_length=20, unique=True)),
                ('last_synced_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_store_sync_watermark',
            },
        ),
    ]
