# Generated by Django 5.1.6 on 2026-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_backfill_store_sync_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesyncwatermark',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
